//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace APIFront.APISP {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Api_GestionSPSoap", Namespace="http://tempuri.org/")]
    public partial class Api_GestionSP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SuscripcionesPorPlanOperationCompleted;
        
        private System.Threading.SendOrPostCallback TotalFacturadoPorClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback IngresosPorPlanOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Api_GestionSP() {
            this.Url = global::APIFront.Properties.Settings.Default.APIFront_APISP_Api_GestionSP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SuscripcionesPorPlanCompletedEventHandler SuscripcionesPorPlanCompleted;
        
        /// <remarks/>
        public event TotalFacturadoPorClienteCompletedEventHandler TotalFacturadoPorClienteCompleted;
        
        /// <remarks/>
        public event IngresosPorPlanCompletedEventHandler IngresosPorPlanCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuscripcionesPorPlan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sp_SuscripcionesPorPlan_Result[] SuscripcionesPorPlan() {
            object[] results = this.Invoke("SuscripcionesPorPlan", new object[0]);
            return ((sp_SuscripcionesPorPlan_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void SuscripcionesPorPlanAsync() {
            this.SuscripcionesPorPlanAsync(null);
        }
        
        /// <remarks/>
        public void SuscripcionesPorPlanAsync(object userState) {
            if ((this.SuscripcionesPorPlanOperationCompleted == null)) {
                this.SuscripcionesPorPlanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuscripcionesPorPlanOperationCompleted);
            }
            this.InvokeAsync("SuscripcionesPorPlan", new object[0], this.SuscripcionesPorPlanOperationCompleted, userState);
        }
        
        private void OnSuscripcionesPorPlanOperationCompleted(object arg) {
            if ((this.SuscripcionesPorPlanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuscripcionesPorPlanCompleted(this, new SuscripcionesPorPlanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TotalFacturadoPorCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sp_TotalFacturadoPorCliente_Result[] TotalFacturadoPorCliente() {
            object[] results = this.Invoke("TotalFacturadoPorCliente", new object[0]);
            return ((sp_TotalFacturadoPorCliente_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void TotalFacturadoPorClienteAsync() {
            this.TotalFacturadoPorClienteAsync(null);
        }
        
        /// <remarks/>
        public void TotalFacturadoPorClienteAsync(object userState) {
            if ((this.TotalFacturadoPorClienteOperationCompleted == null)) {
                this.TotalFacturadoPorClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTotalFacturadoPorClienteOperationCompleted);
            }
            this.InvokeAsync("TotalFacturadoPorCliente", new object[0], this.TotalFacturadoPorClienteOperationCompleted, userState);
        }
        
        private void OnTotalFacturadoPorClienteOperationCompleted(object arg) {
            if ((this.TotalFacturadoPorClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TotalFacturadoPorClienteCompleted(this, new TotalFacturadoPorClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IngresosPorPlan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sp_IngresosPorPlan_Result[] IngresosPorPlan() {
            object[] results = this.Invoke("IngresosPorPlan", new object[0]);
            return ((sp_IngresosPorPlan_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void IngresosPorPlanAsync() {
            this.IngresosPorPlanAsync(null);
        }
        
        /// <remarks/>
        public void IngresosPorPlanAsync(object userState) {
            if ((this.IngresosPorPlanOperationCompleted == null)) {
                this.IngresosPorPlanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIngresosPorPlanOperationCompleted);
            }
            this.InvokeAsync("IngresosPorPlan", new object[0], this.IngresosPorPlanOperationCompleted, userState);
        }
        
        private void OnIngresosPorPlanOperationCompleted(object arg) {
            if ((this.IngresosPorPlanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IngresosPorPlanCompleted(this, new IngresosPorPlanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class sp_SuscripcionesPorPlan_Result {
        
        private string nombre_del_planField;
        
        private System.Nullable<int> número_de_suscripcionesField;
        
        /// <remarks/>
        public string Nombre_del_plan {
            get {
                return this.nombre_del_planField;
            }
            set {
                this.nombre_del_planField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Número_de_suscripciones {
            get {
                return this.número_de_suscripcionesField;
            }
            set {
                this.número_de_suscripcionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class sp_IngresosPorPlan_Result {
        
        private string nombreField;
        
        private System.Nullable<decimal> ingresos_TotalesField;
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Ingresos_Totales {
            get {
                return this.ingresos_TotalesField;
            }
            set {
                this.ingresos_TotalesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class sp_TotalFacturadoPorCliente_Result {
        
        private string nombreField;
        
        private System.Nullable<decimal> total_facturadoField;
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Total_facturado {
            get {
                return this.total_facturadoField;
            }
            set {
                this.total_facturadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SuscripcionesPorPlanCompletedEventHandler(object sender, SuscripcionesPorPlanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuscripcionesPorPlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuscripcionesPorPlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sp_SuscripcionesPorPlan_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sp_SuscripcionesPorPlan_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void TotalFacturadoPorClienteCompletedEventHandler(object sender, TotalFacturadoPorClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TotalFacturadoPorClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TotalFacturadoPorClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sp_TotalFacturadoPorCliente_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sp_TotalFacturadoPorCliente_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void IngresosPorPlanCompletedEventHandler(object sender, IngresosPorPlanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IngresosPorPlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IngresosPorPlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sp_IngresosPorPlan_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sp_IngresosPorPlan_Result[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591